# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
  
sudo: false

addons:
  apt:
    packages:
       - libxml2-dev
       - tk8.5

# env:
#  - any env entry here

r:
  - release
# this has to be removed as soon as possible (I know it will last forever :( )  
warnings_are_errors: false

repos:
  CRAN: http://cran.rstudio.com

r_github_packages:
  - jimhester/covr
  - rstudio/packrat

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - make restore_packrat
  - make test
  - make codecov
  